apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingora
spec:
  selector:
    matchLabels:
      app: pingora
  replicas: 2
  template:
    metadata:
      labels:
        app: pingora
    spec:
      containers:
      - name: pingora
        image: nginx:1.14.2
        ports:
        - containerPort: 80
